[package]
name = "rust-calc"
version = "1.0.0"
authors = ["LebranceBW <LebranceBW@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
